/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.forestcineplex.movieticketbookingsystem.view.panel;

/**
 *
 * @author LENOVO
 */
public class MainEmployee extends javax.swing.JPanel {

    /**
     * Creates new form MainCustomer
     */
    public MainEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUser = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelName = new javax.swing.JLabel();
        jLabelMember = new javax.swing.JLabel();
        jButtonInfo = new javax.swing.JButton();
        jButtonWelcome = new javax.swing.JButton();
        jButtonOrder = new javax.swing.JButton();
        jButtonAddMovie = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonPayment = new javax.swing.JButton();
        jButtonBooking = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();

        setForeground(new java.awt.Color(0, 204, 204));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/man.png"))); // NOI18N
        jPanel1.add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 310, 140));

        jSeparator1.setForeground(new java.awt.Color(51, 102, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 310, 10));

        jLabelName.setBackground(new java.awt.Color(255, 255, 255));
        jLabelName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("Ngo Anh Khoi");
        jPanel1.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 180, 300, -1));
        jLabelName.getAccessibleContext().setAccessibleName("");

        jLabelMember.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMember.setText("Employee");
        jPanel1.add(jLabelMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 160, 300, -1));

        jButtonInfo.setBackground(new java.awt.Color(83, 173, 116));
        jButtonInfo.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jButtonInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info.png"))); // NOI18N
        jButtonInfo.setText("Infomation");
        jButtonInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonInfo.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jPanel1.add(jButtonInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 310, 40));

        jButtonWelcome.setBackground(new java.awt.Color(83, 173, 116));
        jButtonWelcome.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jButtonWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png"))); // NOI18N
        jButtonWelcome.setText("Welcome");
        jButtonWelcome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonWelcome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonWelcome.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jPanel1.add(jButtonWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 310, 40));

        jButtonOrder.setBackground(new java.awt.Color(83, 173, 116));
        jButtonOrder.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jButtonOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food.png"))); // NOI18N
        jButtonOrder.setText("Order Food");
        jButtonOrder.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonOrder.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jPanel1.add(jButtonOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 310, 40));

        jButtonAddMovie.setBackground(new java.awt.Color(83, 173, 116));
        jButtonAddMovie.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jButtonAddMovie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        jButtonAddMovie.setText("Add Movie");
        jButtonAddMovie.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonAddMovie.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonAddMovie.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jPanel1.add(jButtonAddMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 310, 40));

        jButtonEdit.setBackground(new java.awt.Color(83, 173, 116));
        jButtonEdit.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drive.png"))); // NOI18N
        jButtonEdit.setText("Edit Screening");
        jButtonEdit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonEdit.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jPanel1.add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 310, 40));

        jButtonPayment.setBackground(new java.awt.Color(83, 173, 116));
        jButtonPayment.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jButtonPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money.png"))); // NOI18N
        jButtonPayment.setText("Payment");
        jButtonPayment.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonPayment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPayment.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jPanel1.add(jButtonPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 310, 40));

        jButtonBooking.setBackground(new java.awt.Color(83, 173, 116));
        jButtonBooking.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jButtonBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticket.png"))); // NOI18N
        jButtonBooking.setText("Avaible Movie");
        jButtonBooking.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonBooking.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonBooking.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jPanel1.add(jButtonBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 310, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/out.png"))); // NOI18N
        jLabel1.setText("Sign Out");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, -1, -1));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background1_.png"))); // NOI18N
        jLabelBackground.setText("jLabel1");
        jPanel1.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, 0, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, -1));

        jPanelMain.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        add(jPanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 970, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddMovie;
    private javax.swing.JButton jButtonBooking;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JButton jButtonOrder;
    private javax.swing.JButton jButtonPayment;
    private javax.swing.JButton jButtonWelcome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelMember;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
