/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.forestcineplex.movieticketbookingsystem.view.panel;

import com.forestcineplex.movieticketbookingsystem.data.DataConnection;
import com.forestcineplex.movieticketbookingsystem.model.User;
import com.forestcineplex.movieticketbookingsystem.view.frame.LobbySystem;
import com.forestcineplex.movieticketbookingsystem.view.frame.MainSystem;
import com.formdev.flatlaf.FlatLightLaf;
import com.mysql.cj.jdbc.exceptions.CommunicationsException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.UIManager;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author LENOVO
 */
public class MainAdmin extends javax.swing.JPanel {

    /**
     * Creates new form MainCustomer
     */
    private MainSystem mainSystem;
    private User user;
    
    public MainAdmin() {
        initComponents();
    }
    
    public void loadUser() {
        String username = user.getUser();
        String sqlQuery = "SELECT * FROM user WHERE User = ?";
        
        try (ResultSet resultSet = DataConnection.executeQuery(sqlQuery, username)) {
            if (resultSet != null && resultSet.next()) {
                String user1 = resultSet.getString("User");
                String passwordHash1 = resultSet.getString("PasswordHash");
                String role = resultSet.getString("Role");
                String fullName = resultSet.getString("FullName");
                String gender = resultSet.getString("Gender");
                Date birthDate = resultSet.getDate("BirthDate");
                String address = resultSet.getString("Address");
                String phone = resultSet.getString("Phone");
                String mail = resultSet.getString("Mail");
                double salary = resultSet.getDouble("Salary");
                this.user = new User(user1,passwordHash1,role,fullName,gender,salary,address,phone,mail,birthDate);
                mainSystem.setUser(user);
            } 
        } catch (SQLException e) {
            e.printStackTrace(); // Hoặc log lỗi
        }
    }
    
    public void load() {
        loadUser();
        jLabelName.setText(user.getFullname());
        jLabelMember.setText(user.getRole());
        
        String role = user.getRole();
        String gender= user.getGender();
        if (role.equalsIgnoreCase("ADMIN")) {
            if (gender.equalsIgnoreCase("MALE")) {
                jLabelAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin.png")));
            } else {
                jLabelAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/womenAdmin.png")));
            }
        } else {
            if (gender.equalsIgnoreCase("MALE")) {
                jLabelAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/man.png")));
            } else {
                jLabelAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/women.png")));
            }
        }
        
        if (role.equals("Employee")) {
            jButtonManage.setVisible(false);
            jLabelMember.setForeground(new java.awt.Color(0, 0, 0));
            try {
                mainSystem.changeMainPanelWelcome();
            } catch (Exception e) {}
        } else {
            jButtonManage.setVisible(true);
            jLabelMember.setForeground(new java.awt.Color(0, 0, 153));

        }
        
    }
    
    public MainAdmin(MainSystem mainSystem) {
        this.mainSystem = mainSystem;
        this.user = mainSystem.getUser();
        initComponents();
        load();
    }
    
    public void RemoveAllBackgroundButton() {
        jButtonWelcome.setBackground(new java.awt.Color(83, 173, 116));
        jButtonInfo.setBackground(new java.awt.Color(83, 173, 116));
        jButtonAddMovie.setBackground(new java.awt.Color(83, 173, 116));
        jButtonBooking.setBackground(new java.awt.Color(83, 173, 116));
        jButtonEdit.setBackground(new java.awt.Color(83, 173, 116));
        jButtonManage.setBackground(new java.awt.Color(83, 173, 116));
        jButtonOrder.setBackground(new java.awt.Color(83, 173, 116));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAvatar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelName = new javax.swing.JLabel();
        jLabelMember = new javax.swing.JLabel();
        jButtonInfo = new javax.swing.JButton();
        jButtonWelcome = new javax.swing.JButton();
        jButtonOrder = new javax.swing.JButton();
        jButtonAddMovie = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonManage = new javax.swing.JButton();
        jButtonBooking = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();

        setForeground(new java.awt.Color(0, 204, 204));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin.png"))); // NOI18N
        jPanel1.add(jLabelAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 310, 140));

        jSeparator1.setForeground(new java.awt.Color(51, 102, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 310, 10));

        jLabelName.setBackground(new java.awt.Color(255, 255, 255));
        jLabelName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("Ngo Anh Khoi");
        jPanel1.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 180, 300, -1));
        jLabelName.getAccessibleContext().setAccessibleName("");

        jLabelMember.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelMember.setForeground(new java.awt.Color(0, 0, 153));
        jLabelMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMember.setText("Admin");
        jPanel1.add(jLabelMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 160, 300, -1));

        jButtonInfo.setBackground(new java.awt.Color(83, 173, 116));
        jButtonInfo.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jButtonInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info.png"))); // NOI18N
        jButtonInfo.setText("Infomation");
        jButtonInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonInfo.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 310, 40));

        jButtonWelcome.setBackground(new java.awt.Color(66, 139, 93));
        jButtonWelcome.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jButtonWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png"))); // NOI18N
        jButtonWelcome.setText("Welcome");
        jButtonWelcome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonWelcome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonWelcome.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jButtonWelcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWelcomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 310, 40));

        jButtonOrder.setBackground(new java.awt.Color(83, 173, 116));
        jButtonOrder.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jButtonOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food.png"))); // NOI18N
        jButtonOrder.setText("Order Food");
        jButtonOrder.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonOrder.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jButtonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 310, 40));

        jButtonAddMovie.setBackground(new java.awt.Color(83, 173, 116));
        jButtonAddMovie.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jButtonAddMovie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drive.png"))); // NOI18N
        jButtonAddMovie.setText("Edit Screening");
        jButtonAddMovie.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonAddMovie.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonAddMovie.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jButtonAddMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMovieActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 310, 40));

        jButtonEdit.setBackground(new java.awt.Color(83, 173, 116));
        jButtonEdit.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drive.png"))); // NOI18N
        jButtonEdit.setText("Edit Screening");
        jButtonEdit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonEdit.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jPanel1.add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 310, 40));
        jButtonEdit.setVisible(false);

        jButtonManage.setBackground(new java.awt.Color(83, 173, 116));
        jButtonManage.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jButtonManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manage.png"))); // NOI18N
        jButtonManage.setText("Management");
        jButtonManage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonManage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonManage.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jButtonManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 310, 40));

        jButtonBooking.setBackground(new java.awt.Color(83, 173, 116));
        jButtonBooking.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jButtonBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticket.png"))); // NOI18N
        jButtonBooking.setText("Available Movie");
        jButtonBooking.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonBooking.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonBooking.setMargin(new java.awt.Insets(2, 30, 3, 14));
        jButtonBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookingActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 310, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/out.png"))); // NOI18N
        jLabel1.setText("Sign Out");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, -1, -1));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background1_.png"))); // NOI18N
        jLabelBackground.setText("jLabel1");
        jPanel1.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, 0, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, -1));

        jPanelMain.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        add(jPanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 970, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
            LobbySystem lobbySystem = new LobbySystem();
            mainSystem.dispose();
        } catch ( Exception e) {
            e.printStackTrace();
            
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButtonWelcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWelcomeActionPerformed
        // TODO add your handling code here:
        RemoveAllBackgroundButton();
        jButtonWelcome.setBackground(new java.awt.Color(66, 139, 93));
        this.mainSystem.changeMainPanelWelcome();
    }//GEN-LAST:event_jButtonWelcomeActionPerformed

    private void jButtonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderActionPerformed
        // TODO add your handling code here:
        RemoveAllBackgroundButton();
        jButtonOrder.setBackground(new java.awt.Color(66, 139, 93));
        this.mainSystem.changeMainPanelOrderFood();
    }//GEN-LAST:event_jButtonOrderActionPerformed

    private void jButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoActionPerformed
        // TODO add your handling code here:
        RemoveAllBackgroundButton();
        jButtonInfo.setBackground(new java.awt.Color(66, 139, 93));
        this.mainSystem.changeMainPanelInfo();
    }//GEN-LAST:event_jButtonInfoActionPerformed

    private void jButtonManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageActionPerformed
        // TODO add your handling code here:
        RemoveAllBackgroundButton();
        jButtonManage.setBackground(new java.awt.Color(66, 139, 93));
        this.mainSystem.changeMainPanelManagement();
    }//GEN-LAST:event_jButtonManageActionPerformed

    private void jButtonAddMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMovieActionPerformed
        // TODO add your handling code here:
        RemoveAllBackgroundButton();
        jButtonAddMovie.setBackground(new java.awt.Color(66, 139, 93));
        this.mainSystem.changeMainPanelAddMovie();
    }//GEN-LAST:event_jButtonAddMovieActionPerformed

    private void jButtonBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookingActionPerformed
        // TODO add your handling code here:
        RemoveAllBackgroundButton();
        jButtonBooking.setBackground(new java.awt.Color(66, 139, 93));
        mainSystem.changeMainPanelAvailableMovie();
    }//GEN-LAST:event_jButtonBookingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddMovie;
    private javax.swing.JButton jButtonBooking;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JButton jButtonManage;
    private javax.swing.JButton jButtonOrder;
    private javax.swing.JButton jButtonWelcome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAvatar;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelMember;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
