/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.forestcineplex.movieticketbookingsystem.view.frame;

import com.forestcineplex.movieticketbookingsystem.data.DataConnection;
import com.forestcineplex.movieticketbookingsystem.model.ForestCineplexModel;
import com.forestcineplex.movieticketbookingsystem.model.User;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author LENOVO
 */
public class MainSystem extends javax.swing.JFrame {

    /**
     * Creates new form MainSystem
     */
    private User user;
    
    
    public void setUser(User user) {
        this.user = user;
    }
    public void loadMainAdmin() {
        mainAdmin1.load();
    }
    public void changeMainPanelAddMovie() {
        //addMovie1.loadTableMovie();
        addMovie1.SetDefault();
        addMovie1.loadTableMovie();
        panelMain.removeAll();
        panelMain.add(addMovie1);
        panelMain.repaint();
        panelMain.revalidate();
    }
    public void changeMainPanelWelcome() {
        welcome1.loadDashBoard();
        //welcome1.showChart();
        panelMain.removeAll();
        panelMain.add(welcome1);
        panelMain.repaint();
        panelMain.revalidate();
    }
    
    public void changeMainPanelOrderFood() {
        panelMain.removeAll();
        panelMain.add(foodOrder1);
        panelMain.repaint();
        panelMain.revalidate();
    }
    
    public void changeMainPanelInfo() {
        information1.loadUser();
        information1.loadInfo();
        panelMain.removeAll();
        panelMain.add(information1);
        panelMain.repaint();
        panelMain.revalidate();
    }
    
    public void changeMainPanelManagement() {
        management1.setDefault();
        management1.loadTable();
        panelMain.removeAll();
        panelMain.add(management1);
        panelMain.repaint();
        panelMain.revalidate();
    }
    
    public void changeMainPanelAvailableMovie() {
        availableMovie1.setDefalt();
        availableMovie1.loadTable();
        panelMain.removeAll();
        panelMain.add(availableMovie1);
        panelMain.repaint();
        panelMain.revalidate();
    }
    
    
    public void setIcon() {
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/ForestCineplex.png"));
        Image image = imageIcon.getImage();
        setIconImage(image);
    }
    
    public MainSystem(User user) {
        setIcon();
        this.user = user;
        initComponents();
        setResizable(false);
        setVisible(true);
        
    }
    public MainSystem() {
        initComponents();
        setResizable(false);
        setVisible(true);
    }
    
    public User getUser() {
        return this.user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        welcome1 = new com.forestcineplex.movieticketbookingsystem.view.panel.function.Welcome();
        foodOrder1 = new com.forestcineplex.movieticketbookingsystem.view.panel.function.FoodOrder(user);
        information1 = new com.forestcineplex.movieticketbookingsystem.view.panel.function.Information(user);
        management1 = new com.forestcineplex.movieticketbookingsystem.view.panel.function.Management(this);
        addMovie1 = new com.forestcineplex.movieticketbookingsystem.view.panel.function.AddMovie(this);
        availableMovie1 = new com.forestcineplex.movieticketbookingsystem.view.panel.function.AvailableMovie(this);
        mainAdmin1 = new com.forestcineplex.movieticketbookingsystem.view.panel.MainAdmin(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMain.setLayout(new java.awt.CardLayout());
        panelMain.add(welcome1, "card2");
        panelMain.add(foodOrder1, "card3");
        panelMain.add(information1, "card4");
        panelMain.add(management1, "card5");
        panelMain.add(addMovie1, "card6");
        panelMain.add(availableMovie1, "card7");

        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 970, 720));
        getContentPane().add(mainAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.forestcineplex.movieticketbookingsystem.view.panel.function.AddMovie addMovie1;
    private com.forestcineplex.movieticketbookingsystem.view.panel.function.AvailableMovie availableMovie1;
    private com.forestcineplex.movieticketbookingsystem.view.panel.function.FoodOrder foodOrder1;
    private com.forestcineplex.movieticketbookingsystem.view.panel.function.Information information1;
    private com.forestcineplex.movieticketbookingsystem.view.panel.MainAdmin mainAdmin1;
    private com.forestcineplex.movieticketbookingsystem.view.panel.function.Management management1;
    private javax.swing.JPanel panelMain;
    private com.forestcineplex.movieticketbookingsystem.view.panel.function.Welcome welcome1;
    // End of variables declaration//GEN-END:variables
}
